// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_5_enemies_defeated = "CgkI8Z6b1q4ZEAIQEw"; // <GPGSID>
        public const string achievement_10_enemies_defeated = "CgkI8Z6b1q4ZEAIQFA"; // <GPGSID>
        public const string achievement_10_shots_fired = "CgkI8Z6b1q4ZEAIQEA"; // <GPGSID>
        public const string achievement_25_enemies_defeated = "CgkI8Z6b1q4ZEAIQFQ"; // <GPGSID>
        public const string achievement_25_shots_fired = "CgkI8Z6b1q4ZEAIQEQ"; // <GPGSID>
        public const string achievement_50_shots_fired = "CgkI8Z6b1q4ZEAIQEg"; // <GPGSID>
        public const string achievement_defeated_an_enemy = "CgkI8Z6b1q4ZEAIQBA"; // <GPGSID>
        public const string achievement_first_boss_defeated = "CgkI8Z6b1q4ZEAIQAg"; // <GPGSID>
        public const string achievement_more_faster = "CgkI8Z6b1q4ZEAIQDQ"; // <GPGSID>
        public const string achievement_more_wider = "CgkI8Z6b1q4ZEAIQDg"; // <GPGSID>
        public const string achievement_second_boss_defeated = "CgkI8Z6b1q4ZEAIQAw"; // <GPGSID>
        public const string achievement_you_died = "CgkI8Z6b1q4ZEAIQBQ"; // <GPGSID>
        public const string event_enemies_defeated = "CgkI8Z6b1q4ZEAIQCA"; // <GPGSID>
        public const string event_shots_fired = "CgkI8Z6b1q4ZEAIQCg"; // <GPGSID>
        public const string event_total_deaths = "CgkI8Z6b1q4ZEAIQCQ"; // <GPGSID>
        public const string event_total_wins = "CgkI8Z6b1q4ZEAIQDw"; // <GPGSID>
        public const string leaderboard_enemies_defeated = "CgkI8Z6b1q4ZEAIQBg"; // <GPGSID>
        public const string leaderboard_level_complete_time = "CgkI8Z6b1q4ZEAIQBw"; // <GPGSID>

}

